services:
  web:
    build:
      context: ../../../../mynginx
      dockerfile: Dockerfile
    image: mynginx:latest
    container_name: mynginx
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/default.conf:/etc/nginx/http.d/default.conf:ro
      - ./html:/usr/share/nginx/html:ro

    restart: unless-stopped